CREATE TABLE IF NOT EXISTS companies (
 	 id SERIAL PRIMARY KEY,
	 name VARCHAR(255) NOT NULL UNIQUE,
	 description TEXT,
	 website TEXT, 
	 location TEXT, 
	 logo TEXT, 
	 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
